apiVersion: v1
kind: Service
metadata:
  name: userMgt-restapi-lb-svc
  namespace: staging
spec:
  type: LoadBalancer
  selector:
    app: userMgt-restapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    - protocol: TCP
      port: 80
      targetPort: 8005
    - protocol: TCP
      port: 80
      targetPort: 3000