apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: userMgt-restapi-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userMgt-restapi
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70